Create the DAO pool component in the application
api3dao/api3-web-client pull request #15
Opened 2021-05-04 15:08 UTC by Peartes

This commit creates the DAO pool component in the application in an attempt to closes #2 

-> The current component is mostly static and those not read from the blockchain asides from the total staked value which is currently being read from the blockchain

-> The chart component has been left out temporarily while we think out how to implement it

2021-05-05 05:55 UTC, gwn commented on .gitignore
> +.prettierrc
We don't use Prettier in this project yet so I suggest you putting this to you global Git ignore file if you are making use of it personally: https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

2021-05-05 06:00 UTC, gwn commented on src/scenes/Landing.js
> +// Import the DAOPool scene
Let's not comment the obvious :)

2021-05-05 06:07 UTC, gwn commented on src/scenes/DaoPool/index.js
> +                            {fmtApi3(web3.apy || BigNumber.from(0))}%
We no longer need this `|| BigNumber.from(0)` fallback as I introduced the concept of default values to stateVars yesterday. Please see the relevant commit and read the description: https://github.com/api3dao/api3-web-client/commit/532abdd8fb2b40278d7898df4c7b4d0d6d02b164

2021-05-05 06:08 UTC, gwn commented on src/scenes/DaoPool/index.js
> +                            {fmtApi3(web3.ait || BigNumber.from(0))}%
Same as above, we don't need this `|| BigNumber.from(0)` expression anymore.

2021-05-05 06:08 UTC, gwn commented on src/scenes/DaoPool/index.js
> +                            {fmtApi3(web3.totalStake || BigNumber.from(0))}
Same as above, we don't need this || BigNumber.from(0) expression anymore.

2021-05-05 06:08 UTC, gwn commented on src/scenes/DaoPool/index.js
> +                            {fmtApi3(web3.stakeTarget || BigNumber.from(0))}
Same as above, we don't need this || BigNumber.from(0) expression anymore.

2021-05-05 06:10 UTC, gwn requested changes
Thank you, this is much better. We're getting close, please address my comments.

2021-05-05 06:33 UTC, gwn commented on src/lib/web3/config.js
> +    ait: {
There should be a new line before this line, as there is before all new state variable declarations.

2021-05-05 06:36 UTC, gwn commented on src/lib/web3/config.js
> +
There are 3 whitespace characters in this line that we cannot see here in this interface, but need to be removed. Please configure your IDE to show you empty spaces in its Git diff mode, and please don't commit unnecessary empty spaces.

2021-05-05 06:51 UTC, Peartes commented on src/scenes/Landing.js
> +// Import the DAOPool scene
😂 sure

2021-05-05 06:56 UTC, Peartes commented on .gitignore
> +.prettierrc
Got it

2021-05-05 07:03 UTC, Peartes commented on src/lib/web3/config.js
> +
Okay, I'll configure the IDE to do that.  I cannot see the whitespaces

2021-05-05 07:07 UTC, Peartes commented on src/scenes/DaoPool/index.js
> +                            {fmtApi3(web3.apy || BigNumber.from(0))}%
Okay seen the commit, I'll adjust these

2021-05-05 10:00 UTC, gwn commented on src/lib/web3/config.js
> +
Thank you. But in the end this isn't our biggest issue so if you can't quickly find a way to display those whitespaces in your Git diff / in the editor, you can deal with it later too.

2021-05-05 11:12 UTC, gwn commented
Note: I needed to deploy a working DAO Pool so I committed one to the master: https://github.com/api3dao/api3-web-client/commit/4f46e69b03cc6e932ebf7bf77781f34acf938d0e

We will merge this one on top of it when ready.

2021-05-05 11:15 UTC, gwn commented
> Note: I needed to deploy a working DAO Pool so I committed one to the master: [4f46e69](https://github.com/api3dao/api3-web-client/commit/4f46e69b03cc6e932ebf7bf77781f34acf938d0e)
> 
> We will merge this one on top of it when ready.

Also please copy the new formulas from that commit, as the formulas here aren't working properly.

2021-05-05 11:19 UTC, gwn commented on src/lib/web3/config.js
> +                    .add((await totalSupply)).mul(100))
I have to ask; is there a specific reason you're not awaiting at the declaration time? Like why not `let currApy = await contracts.pool.currentApr()`?

Because if you don't do that, `currApy` is not really the APY value but a Promise of it, so it should be named `currApyPromise`.

I want to understand why you are delaying `await`ing until the time you use the value. If there is no specific reason, it is fine too. I just want to know because this is confusing me.

2021-05-05 17:51 UTC, Peartes commented on src/lib/web3/config.js
> +                    .add((await totalSupply)).mul(100))
I want all to kick off the function executions at once rather than wait for each to complete. I'll rename these variables appropriately

2021-05-22 07:38 UTC, gwn commented
This is no longer needed, but thank you very much for your efforts.

2021-05-22 07:38 UTC, closed without merging